version: 1

pipelines:
  default:
    - step:
        name: Build
        script:
          - echo "Building the project..."
          - # Add build commands here
          - echo "Build completed."
    - step:
        name: Test
        script:
          - echo "Running tests..."
          - # Add test commands here
          - echo "Tests passed."
