version: 1

pipelines:
  default:
    - step:
        name: Build
        script:
          - echo "Building the project..."
          - npm install
          - npm run build
          - echo "Build completed."
    - step:
        name: Test
        script:
          - echo "Running tests..."
          - npm test
          - echo "Tests passed."